### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by prokaktus** [constverum/ProxyBroker#10]
What do you think?

_hi from python slack chat!_

**Comment by constverum** [comment]
Hi! =)
I think it's a great idea. And the CLI is implemented in the dev version.

> pip install -U git+https://github.com/constverum/ProxyBroker.git@dev
> proxybroker -h

**Comment by kiroffYT** [comment]
> Hi! =) I think it's a great idea. And the CLI is implemented in the dev version.
> 
> > pip install -U git+https://github.com/constverum/ProxyBroker.git
> > proxybroker -h

```
C:\Users\Home\Downloads\PBroker>proxybroker -h
"proxybroker" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
```

how to fix?
