### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by ivankmk** [constverum/ProxyBroker#101]
`Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/0ymtw0mx3nxfl79dqqd1g9c40000gn/T/pip-install-fgh2ipsa/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kd/0ymtw0mx3nxfl79dqqd1g9c40000gn/T/pip-record-2fhzhtit/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kd/0ymtw0mx3nxfl79dqqd1g9c40000gn/T/pip-install-fgh2ipsa/pycares/`

**Comment by constverum** [comment]
Please try to update to the latest version. And provide more details if the issue still exists.
