### ISSUE TITLE
find proxy in what order?

### ISSUE THREAD

**Issue by gMan1990** [constverum/ProxyBroker#104]
Find by website list in order and per page of website in order?
or just random in each app startup to make request more dispersion？

**Comment by constverum** [comment]
Yes, there is a predefined search order, you can see it [here](https://github.com/constverum/ProxyBroker/blob/ce6b3c8522ff07a4e00ef6b345b50f1ae822cb08/proxybroker/providers.py#L617). The same logic for a [list of pages](https://github.com/constverum/ProxyBroker/blob/ce6b3c8522ff07a4e00ef6b345b50f1ae822cb08/proxybroker/providers.py#L158-L160) for any provider(proxy source).

**Comment by gMan1990** [comment]
so can add a ```random``` option to to make request more dispersion and randomly?
