### ISSUE TITLE
proxy check

### ISSUE THREAD

**Issue by atimofeev86** [constverum/ProxyBroker#107]
I install proxybroker.
then I run command:
proxybroker find --types SOCKS5 -o /var/www/html/secret/proxybroker/2019-01-29
and get 366 proxyies.
Then I manull check all proxy and get only 17 work proxy.
Did I understand correctly that the "find" command does not perform a proxy check?

**Comment by cbastienbaron** [comment]
the project is still maintained ?

**Comment by cbastienbaron** [comment]
The same pbl of checking proxy is also false on HTTP/HTTPS proxy type

**Comment by constverum** [comment]
@atimofeev86 could you please provide your file with proxies so I can reproduce the issue?
@cbastienbaron yes, the project is still maintained =)

**Comment by cbastienbaron** [comment]
Lov this project ! can you please provide a stable release on https://pypi.org/search/?q=proxybroker ?

**Comment by constverum** [comment]
@cbastienbaron a stable release was [published yesterday](https://pypi.org/project/proxybroker/), so you can easily install/update it by ``pip install -U proxybroker``

**Comment by constverum** [comment]
Closed due to inactivity.
