### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Vyrgul** [constverum/ProxyBroker#112]
![screenshot_1](https://user-images.githubusercontent.com/42622980/54004899-1d78b480-4136-11e9-9fd3-efd903de0fd6.png)

**Comment by GooDeeJaY** [comment]
I'm getting this error too(

**Comment by gitxmax** [comment]
Get the same error, seems to be related to aiodns.
I tried different python versions, no hope...
To the topic starter, why not to put the error into the title? This would probably help with getting the issue solved.

**Comment by artgod1** [comment]
the same error here

**Comment by constverum** [comment]
Fixed in v0.3.2
