### ISSUE TITLE
raise RuntimeError('Could not get the external IP')

### ISSUE THREAD

**Issue by oplus** [constverum/ProxyBroker#132]
Hello,

I tried to use [find_an_save.py](https://github.com/constverum/ProxyBroker/blob/master/examples/find_and_save.py) example in my code to occasionally produce a list of proxies. After calling the main function and getting the proxy file successfully few times, I get below error. I tried every work around I could think of without success, even exception handling and recalling the function in a new scope does not help. I do not understand asyncio-await routine so I am not able to play with it's related code. 

`  File "proxygetter.py", line 6, in <module>
    proxyer.main()
  File "/root/Desktop/Projects/forexfactory/proxyer.py", line 25, in main
    loop.run_until_complete(tasks)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/proxybroker/api.py", line 173, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/usr/local/lib/python3.7/dist-packages/proxybroker/resolver.py", line 109, in get_real_ext_ip
    raise RuntimeError('Could not get the external IP')
RuntimeError: Could not get the external IP
`

**Comment by MikeZ77** [comment]
So after proxybroker throws the RuntimeError, is it the case that the event loop does not exit/hangs? If so you can checkout my answer to issue #127

**Comment by oplus** [comment]
Strangely, I can't reproduce the error now. I think It is somehow related to [#25](https://github.com/constverum/ProxyBroker/issues/25). Thank you @MikeZ77 I will try your solution when I am able to produce it again.
