### ISSUE TITLE
proxybroker command is missing

### ISSUE THREAD

**Issue by jabbalaci** [constverum/ProxyBroker#15]
If I install the project with `pip install proxybroker`, the command `proxybroker` is missing. If I install the dev. version directly from github, the `proxybroker` is there.

Either update the pypi version or mention this strangeness in the documentation. BTW, thanks for the project, it'll be useful for me.

**Comment by constverum** [comment]
Thanks for your attention @jabbalaci!
I certainly didn't plan to keep the 2.0 version in beta for so long =)
It seems no serious problems over several months of testing were not detected. So I will try to release version 2.0 on next week and update it on pypi.

**Comment by tomtom87** [comment]
having the same problem will install from github then thanks @jabbalaci

**Comment by megapro17** [comment]
so far problem exist

**Comment by constverum** [comment]
Thank you for your patience! ;) The latest version of is now available on pypi (you can use pip to install it).
