### ISSUE TITLE
Error Installing Through pip

### ISSUE THREAD

**Issue by 57ra7363m** [constverum/ProxyBroker#2]
I tried to install through pip and received the following error:

Collecting proxybroker
  Using cached proxybroker-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-CX9FBL/proxybroker/setup.py", line 10, in <module>
        VERSION = **import**(PACKAGE).**version**
      File "proxybroker/**init**.py", line 2
    SyntaxError: Non-ASCII character '\xc2' in file proxybroker/**init**.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CX9FBL/proxybroker

**Comment by uthunderbird** [comment]
This project uses `async/await` syntax, so it requires Python 3. And not just any Python 3, but only the last one branch, Python 3.5. You can't install it using pip from Python 2.

**Comment by constverum** [comment]
@uthunderbird is right, this error occurs because you're trying to install the project in an environment with Python 2. But requires Python 3.5+

**Comment by 57ra7363m** [comment]
Yep, that fixed it.  Stupid mistake on my part, not reading the documentation carefully.  Deployed through the simple script example on the project page and it works great.

**Comment by laruellef** [comment]
Love this project, well done!
It'd be nice to have support for python 2.7.x tho...

**Comment by Mehran** [comment]
```
# pip3 install proxybroker
Requirement already satisfied: proxybroker in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: aiohttp in /usr/local/lib/python3.5/dist-packages (from proxybroker)
Requirement already satisfied: aiodns in /usr/local/lib/python3.5/dist-packages (from proxybroker)
Requirement already satisfied: maxminddb in /usr/local/lib/python3.5/dist-packages (from proxybroker)
Requirement already satisfied: async_timeout>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from aiohttp->proxybroker)
Requirement already satisfied: multidict>=2.1.4 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
Requirement already satisfied: yarl<0.11,>=0.10.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
Requirement already satisfied: pycares>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from aiodns->proxybroker)

# proxybroker
bash: proxybroker: command not found

```

**Comment by NurdTurd** [comment]
@constverum can we get some help for @Mehran? I have the same problem. ^^

**Comment by constverum** [comment]
Thank you for your patience! ;) The latest version of is now available on pypi (you can use pip to install it).

**Comment by Tomkhalifa** [comment]
@constverum plzz help me i install proxy broker but later it's show again download proxy broker

**Comment by oldkingcone** [comment]
> ```
> # pip3 install proxybroker
> Requirement already satisfied: proxybroker in /usr/local/lib/python3.5/dist-packages
> Requirement already satisfied: aiohttp in /usr/local/lib/python3.5/dist-packages (from proxybroker)
> Requirement already satisfied: aiodns in /usr/local/lib/python3.5/dist-packages (from proxybroker)
> Requirement already satisfied: maxminddb in /usr/local/lib/python3.5/dist-packages (from proxybroker)
> Requirement already satisfied: async_timeout>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
> Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from aiohttp->proxybroker)
> Requirement already satisfied: multidict>=2.1.4 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
> Requirement already satisfied: yarl<0.11,>=0.10.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp->proxybroker)
> Requirement already satisfied: pycares>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from aiodns->proxybroker)
> 
> # proxybroker
> bash: proxybroker: command not found
> ```

you need to make sure $HOME/.local/bin is in your path.
