### ISSUE TITLE
Fail to pull local proxy list ffrom http://127.0.0.1:8000/proxy.txt

### ISSUE THREAD

**Issue by ksantr** [constverum/ProxyBroker#22]
Initially I need to check my local proxy list. So I set "http://127.0.0.1:8000/proxy.txt/" in my providers list. But ProxyBroker returns 0 proxies.

**Comment by uthunderbird** [comment]
Are you sure that you should check `http://127.0.0.1:8000/proxy.txt/` instead of `http://127.0.0.1:8000/proxy.txt`?
