### ISSUE TITLE
Get more location info

### ISSUE THREAD

**Issue by PowerPress** [constverum/ProxyBroker#26]
Could it use maxminds geo ip database or another source to show which city/state of the proxy in addition to country?

**Comment by gabrielgradinaru** [comment]
The GeoLite2-City.mmdb database has 51MB uncompressed and in my opinion it doesn't make sense to have in the repo.

**Comment by constverum** [comment]
@PowerPress thanks for your attention!
Now to get additional geolocation information, you can run once `proxybroker update-geo` command to update the GeoIP database (to _City_ version).
