### ISSUE TITLE
--type flag should be case insensitive

### ISSUE THREAD

**Issue by ssbtoday** [constverum/ProxyBroker#27]
Python Version: Python 3.5.2
Proxybroker Version: proxybroker 0.2.0b3

## Current Behavior
`proxybroker find --types socks4 --countries US --limit 10`
`proxybroker find: error: argument --types: invalid choice: 'socks4' (choose from 'HTTP', 'HTTPS', 'SOCKS4', 'SOCKS5', 'CONNECT:80', 'CONNECT:25')`

## Expected Behavior
proxybroker will detect the type from CLI without parsing case sensitivity.

**Comment by constverum** [comment]
Done.
