### ISSUE TITLE
--providers flag not working from cli

### ISSUE THREAD

**Issue by vaibhav8275** [constverum/ProxyBroker#29]
proxybroker --max-conn 10 --providers ['http://txt.proxyspy.net/proxy.txt', 'http://skypegrab.net/proxy/http.txt'] find --types HTTP HTTPS --lvl High --countries US --strict -l 10

or

proxybroker --max-conn 10 --providers 'http://txt.proxyspy.net/proxy.txt', 'http://skypegrab.net/proxy/http.txt' find --types HTTP HTTPS --lvl High --countries US --strict -l 10

Getting Below Error:
proxybroker: error: argument command: invalid choice: 'HTTP' (choose from 'find', 'grab', 'serve')

**Comment by constverum** [comment]
@vaibhav8275 thank you for the feedback! 
Fixed. Now you can just split providers (pass them one by one): `proxybroker --max-conn 10 --provider http://txt.proxyspy.net/proxy.txt --provider http://skypegrab.net/proxy/http.txt find --types HTTP -l 10`
