### ISSUE TITLE
DeprecationWarning at starting

### ISSUE THREAD

**Issue by Shazgul** [constverum/ProxyBroker#35]
Used Command:
`$ proxybroker find --types HTTP HTTPS --lvl High --countries DE CH AT --strict`

Error Message:
```
/usr/local/lib/python3.5/dist-packages/aiohttp/client.py:565: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
```

ProxyBroker is starting & everything is just working fine, but it always gives me this Error, but why?

**Comment by DataPools** [comment]
I used pull request #28

**Comment by vladiscripts** [comment]
I've too does not work ProxyBroker with the same error. If I'm not mistaken, this commit is not included in the master and dev branches. I'm not good in git. How to update the version and restore the work?

My run of it:
`$ proxybroker find --types HTTP HTTPS --lvl High --countri DE CH AT --strict`
```
.. /python3.6/site-packages/aiohttp/client.py:576: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
.. /python3.6/site-packages/aiohttp/helpers.py:129: DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)
```
...and the program hangs. 
Errors like it with other commands, and on run it as framework from a script.

**Comment by constverum** [comment]
Fixed.
