### ISSUE TITLE
Aiohttp 2.1.0 bug

### ISSUE THREAD

**Issue by kolyanok** [constverum/ProxyBroker#36]
ProxyBroker doesn't works after updating aiohttp to 2.1.0...
OS: macOS Sierra 10.12.4.
Python: 3.5, 3.6.

**Comment by Legacier** [comment]
Same here, doesn't works after updating. I downgraded to aiohttp 2.0.7 and it worked again.
OS: Archlinux
Python: 3.6

**Comment by constverum** [comment]
Try to update aiohttp to current version.
