### ISSUE TITLE
Output when `--outfile`

### ISSUE THREAD

**Issue by erm3nda** [constverum/ProxyBroker#39]
I've see that outfile is not being written until whole process has finished.
I tried `| tee` piping but output did not work.

Tried many things but can't make it work. 

The reason to fill this issue, is because i can't know in real time how many proxies do i have "in process" (to be written to file) ... so it's a quite blinded process...

**Comment by cachethemall** [comment]
I would like to add a suggestion:

The current output format is:

> <Proxy GB 0.48s [HTTP: Anonymous] 45.77.90.15:3128>
> <Proxy DE 0.49s [HTTP: High] 136.243.145.232:3128>
> ...

If there is an option for JSON lines format (http://jsonlines.org), that would be easier to parse later. For an example:

> {"proxy": "45.77.90.15:3128", "country": "GB", "type": "HTTP", "level": "Anonymous"}
> {"proxy": "136.243.145.232:3128", "country": "DE", "type": "HTTP", "level": "High"}
> ...

**Comment by erm3nda** [comment]
I added buffering and now flushes to file ok. Now i can run under `timeout` and file will survive.
