### ISSUE TITLE
Fail to run basic example

### ISSUE THREAD

**Issue by fygul** [constverum/ProxyBroker#4]
Run [basic example](https://github.com/constverum/ProxyBroker#basic-example) on Windows 8, python 3.5.1
aiodns==1.0.1
aiohttp==0.21.5
chardet==2.3.0
maxminddb==1.2.0
proxybroker==0.1.2
pycares==1.0.0

Error message:
> D:\Temp\proxybroker\venv\Scripts\python.exe D:/Temp/proxybroker/example.py
> Traceback (most recent call last):
>   File "D:/Temp/proxybroker/example.py", line 7, in <module>
>     broker = Broker(proxies, loop=loop)
>   File "D:\Temp\proxybroker\venv\lib\site-packages\proxybroker\api.py", line 45, in __init__
>     self._setup(timeout, attempts_conn, max_concurrent_conn, verify_ssl)
>   File "D:\Temp\proxybroker\venv\lib\site-packages\proxybroker\api.py", line 53, in _setup
>     self._loop.add_signal_handler(signal.SIGINT, self._done)
>   File "D:\ProgramFiles\Python35\lib\asyncio\events.py", line 472, in add_signal_handler
>     raise NotImplementedError
> NotImplementedError

**Comment by constverum** [comment]
@fygul thank you for feedback!

The error raised because the function [add_signal_handler() is not supported on Windows ](https://docs.python.org/3.5/library/asyncio-eventloops.html#windows) =(

I made the necessary fix in release 0.1.3. Please update your version and it will work.

**Comment by fygul** [comment]
New version works, it's amazing.

**Comment by radioactivehuman** [comment]
still getting that error

```
`From cffi callback <function _sock_state_cb at 0x03A8F970>:
Traceback (most recent call last):
  File "C:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\users\user\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError`

```
