### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by vladiscripts** [constverum/ProxyBroker#41]
My run of it:
`$ proxybroker find --types HTTP HTTPS --lvl High --countri DE CH AT --strict`
```
.. /python3.6/site-packages/aiohttp/client.py:576: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
.. /python3.6/site-packages/aiohttp/helpers.py:129: DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)
```
...and the program hangs. 
Errors like it with other commands, and on run it as framework from a script.

**Comment by nitheesh** [comment]
The problem was with **aiohttp** package version.
Uninstall the latest version of aiohttp first.
`pip3 uninstall aiohttp`
Install version 2.0.7
`pip3 install aiohttp==2.0.7`

**Comment by vladiscripts** [comment]
Unfortunately, this not helped for me. There also need patch #28. So, I uninstalled this ProxyBroker, and reinstall from the patched fork https://github.com/Lookyan/ProxyBroker.

**Comment by adharna** [comment]
Same issue here

**Comment by constverum** [comment]
Fixed.
