### ISSUE TITLE
DeprecationWarning: Use async with instead issues on windows with python 3 Anaconda

### ISSUE THREAD

**Issue by iamthemanwhoisthere** [constverum/ProxyBroker#43]
C:\Users\Anaconda3\python.exe "C:/Users/PycharmProjects/untitled4/Proxy Checker.py"
C:\Users\Anaconda3\lib\site-packages\aiohttp\client.py:576: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Anaconda3\lib\site-packages\aiohttp\helpers.py:139: DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)

**Comment by constverum** [comment]
Fixed.
