### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by LionOpeter** [constverum/ProxyBroker#52]
I get:
> $ pip install proxybroker
> Collecting proxybroker
>   Using cached proxybroker-0.2.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     zip_safe flag not set; analyzing archive contents...
>     
>     Installed /tmp/pip-build-FKQ8Z_/proxybroker/.eggs/pytest_runner-2.12.1-py2.7.egg
>     error in proxybroker setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FKQ8Z_/proxybroker/

and 

> $ pip install -U git+https://github.com/constverum/ProxyBroker.git
> Collecting git+https://github.com/constverum/ProxyBroker.git
>   Cloning https://github.com/constverum/ProxyBroker.git to /tmp/pip-zcYk3h-build
>     Complete output from command python setup.py egg_info:
>     zip_safe flag not set; analyzing archive contents...
>     
>     Installed /tmp/pip-zcYk3h-build/.eggs/pytest_runner-2.12.1-py2.7.egg
>     error in proxybroker setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zcYk3h-build/

What should i do?

**Comment by constverum** [comment]
@LionOpeter please provide some details about your environment: operating system, python version (`python --version`) and pip version  (`pip --version`).

**Comment by LionOpeter** [comment]
Ok i solved this one myself as i've been working on it for about an hour or so.
The problem was my pip was pip2:

> $ pip3 -V
> The program 'pip3' is currently not installed. You can install it by typing:
> sudo apt install python3-pip

 and i needed pip3 so i installed it:

> $ sudo apt install python3-pip
> [lines indicating an installation is in progress]
> $ pip3 -V
> pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)

and then used it:
> $ pip3 install -U git+https://github.com/constverum/ProxyBroker.git
> $ /home/<USER>/.local/bin/proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10
> [a few lines appeared]

please make a note for the users that they need to have pip3 for this to be installed

**Comment by constverum** [comment]
> please make a note for the users that they need to have pip3 for this to be installed

from _README.rst_
> **Requirements**
> **Python 3.5 or higher**

;)
