### ISSUE TITLE
Backup IP checkers

### ISSUE THREAD

**Issue by Serasar** [constverum/ProxyBroker#53]
As far as I understand reading proxybroker/resolver.py it only uses http://httpbin.org/ to check IP. Maybe you should use some backup IP checking sites in case httpbin.org is down. I suggest http://freegeoip.net/ and some proxy judges:http://www.proxyjudge.info/, http://proxyjudge.us/, http://azenv.net/

**Comment by constverum** [comment]
> Maybe you should use some backup IP checking sites in case httpbin.org is down.

@Serasar It seems you talking about the old implementation. Currently ProxyBroker uses a few sites to get an external IP:
https://github.com/constverum/ProxyBroker/blob/2aab3e8577206961bf4e37c1b45b4c1f807e51c1/proxybroker/resolver.py#L30-L39
The problem has already been discussed - #25

**Comment by Serasar** [comment]
I see, sorry for bothering. Should probably update pypi of broxebroker.
