### ISSUE TITLE
Issue installing proxybroker

### ISSUE THREAD

**Issue by Flixter1** [constverum/ProxyBroker#55]
I've tried to install proxybroker and got following error:

error in proxybroker setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w5/nwdvwf2j6mz1dp95y2fwtjb00000gn/T/pip-build-4gORWY/proxybroker/

**Comment by constverum** [comment]
Please read the *README* file and use python 3.5+

> **Requirements**
> **Python 3.5 or higher**

Duplicate https://github.com/constverum/ProxyBroker/issues/52
