### ISSUE TITLE
More info on Broker.serve()

### ISSUE THREAD

**Issue by lameei** [constverum/ProxyBroker#60]
I just take a look into [examples](http://proxybroker.readthedocs.io/en/latest/examples.html?highlight=Broker.serve()) and I see that there is a mention for Broker.serve() which I couldn't find it. Where is this Broker.serve() and how can I use it?

**Comment by constverum** [comment]
Please check the last code sample on the examples page or just look [here](https://github.com/constverum/ProxyBroker/blob/master/examples/proxy_server.py).

**Comment by sergylog** [comment]
I have run the server using the following:
`proxybroker serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --max-resp-time 2`
How can I now access data from this server?
When I try to do something like this `requests.get('http://127.0.0.1:8888')` I get the response <Response [504]>
