### ISSUE TITLE
I cant install proxybroker from pip

### ISSUE THREAD

**Issue by S1XT3EN** [constverum/ProxyBroker#71]

**Comment by S1XT3EN** [comment]
.6/src/pycares.o
    In file included from src/pycares.c:2:
    src/pycares.h:7:10: fatal error: 'Python.h' file not found
    #include "Python.h"
             ^~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-c0snfvg2/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-7r1oj4y_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-c0snfvg2/pycares/

**Comment by erm3nda** [comment]
You can fix your whole problem with a single Google search. I should not be here asnwering you at all, but here we go.

Python.h is header file, which is a source file to use when compiling. You need to install python-dev package before, in that case, python3-dev. Name of the packages differs a lot between distros.

**Comment by S1XT3EN** [comment]
How to install python3-dev ?

**Comment by erm3nda** [comment]
Which Linux do you have? that's the main question here because every distro
has it's package manager.

~~ Self signed ~~


2018-04-09 13:30 GMT+02:00 S1XT3EN <notifications@github.com>:

**Comment by S1XT3EN** [comment]
I want install it on Termux

**Comment by erm3nda** [comment]
Sorry man, Termux is an terminal emulator??? 

I am asking about the operating system that you is using to install/compile ProxyBroker...

**Comment by S1XT3EN** [comment]
Yeah

**Comment by erm3nda** [comment]
Stop kidding. Tell me which Operating System it's you using man. Didi you read all my 2 (two) phrases??
If you can't reply properly i will just ignore this thread.

**Comment by erm3nda** [comment]
Seeing part of your commands "Command "/data/data/com.termux/files/usr/bin/python -u -c" i see you're triying to compile it from within Android directly. I am not sure right now if you can do what you're trying.
I may come with a reply much later, can't digg that right now.

Try using "pip install python3-dev" from termux but i don't really know what Termux includes. 

In short, you need to install devel package to have source files *.h, then it will be able to found them and compile. I never tried to compile ProxyBroker inside mobile so i can't just say you howto. I must try first.

**Comment by erick08** [comment]
@AkashSawarkar 
@giriraj039
