### ISSUE TITLE
problem in proxybroker

### ISSUE THREAD

**Issue by erick08** [constverum/ProxyBroker#72]
I can not install Proxybroker to fix:

Traceback (most recent call last):
File "hackinsta.py", line 10, in 
from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'

When I try to install, this appears:

$ pip install proxybroker
Collecting proxybroker
Using cached proxybroker-0.3.1-py3-none-any.whl
Requirement already satisfied: maxminddb==1.3.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Collecting aiodns==1.1.1 (from proxybroker)
Using cached aiodns-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: async-timeout==2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Requirement already satisfied: aiohttp==3.0.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Collecting pycares>=1.0.0 (from aiodns==1.1.1->proxybroker)
Using cached pycares-2.3.0.tar.gz
Requirement already satisfied: attrs>=17.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: multidict<5.0,>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: idna-ssl>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: idna>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.0.1->proxybroker)
Installing collected packages: pycares, aiodns, proxybroker
Running setup.py install for pycares ... error
Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;file='/data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-mbjj8xfa-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build/lib.linux-armv7l-3.6
creating build/lib.linux-armv7l-3.6/pycares
copying pycares/init.py -> build/lib.linux-armv7l-3.6/pycares
copying pycares/main.py -> build/lib.linux-armv7l-3.6/pycares
copying pycares/errno.py -> build/lib.linux-armv7l-3.6/pycares
copying pycares/_version.py -> build/lib.linux-armv7l-3.6/pycares
running build_ext
building 'pycares._core' extension
creating build/temp.linux-armv7l-3.6
creating build/temp.linux-armv7l-3.6/src
creating build/temp.linux-armv7l-3.6/deps
creating build/temp.linux-armv7l-3.6/deps/c-ares
creating build/temp.linux-armv7l-3.6/deps/c-ares/src
arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-armv7l-3.6/src/pycares.o
In file included from src/pycares.c:2:
In file included from src/pycares.h:7:
/data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found
#include <crypt.h>
^~~~~~~~~
1 error generated.
error: command 'arm-linux-androideabi-clang' failed with exit status 1

----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;file='/data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-mbjj8xfa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/

If you can help me, I appreciate it.

@avramit
@constverum

**Comment by erm3nda** [comment]
Your problem it's cited on the output: /data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found.

You need the header files to the module using crypt.h. In theory you need to install package libcrypt-devel or look for a precompile wheel provinding modue crypt.

**Comment by 2kwattz** [comment]
experincing same problem

**Comment by constverum** [comment]
@bluegangsta78 please check https://github.com/constverum/ProxyBroker/issues/73#issuecomment-384182880

**Comment by z0rs** [comment]
mengalami masalah yang sama

**Comment by capje** [comment]
raceback (most recent call last):
  File "hackinsta.py", line 9, in <module>
    import requests
