### ISSUE TITLE
proxybroker install *********

### ISSUE THREAD

**Issue by mohammadaliazizkhani** [constverum/ProxyBroker#73]
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;file='/data/data/com.termux/files/usr/tmp/pip-install-guicszbo/pycares/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-es52rl_f/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-guicszbo/pycares/

I entered command pip install proxybroker then it shows such error i tried it on 6 devices. Please help me get out of this error

**Comment by constverum** [comment]
The project is not designed to work on mobile devices (including Android, on which you are trying to run it). #71 #72
