### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by Dextinator** [constverum/ProxyBroker#79]
Hello, at first I want to say that i love the idea behind this project! 
I step up the server with the following settings, but if I want to enter a site I get the error "Your connection is not secure" :proxybroker serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High

Thank you very much for your help!

**Comment by synchronizing** [comment]
If you are using a browser to navigate with proxies this is a normal occurrence. Remember that these are public proxies, and some won't have proper SSL certificates embedded. If you simply want to navigate the web with proxies I would suggest instead checking out some Tor related projects.

**Comment by oldkingcone** [comment]
if not a pure VPN entirely.
