### ISSUE TITLE
Port to node.js

### ISSUE THREAD

**Issue by Revadike** [constverum/ProxyBroker#86]
Will it happen? 🤞

**Comment by constverum** [comment]
Nope =) I suppose it doesn't make sense, because there are already exist [analogs written in JS](https://github.com/search?l=JavaScript&o=desc&q=proxy+find&s=stars&type=Repositories).

**Comment by Revadike** [comment]
> Nope =) I suppose it doesn't make sense, because there are already exist [analogs written in JS](https://github.com/search?l=JavaScript&o=desc&q=proxy+find&s=stars&type=Repositories).

None seem to be as good as yours, but please let me know if im wrong.
