### ISSUE TITLE
support for SMTP check

### ISSUE THREAD

**Issue by laruellef** [constverum/ProxyBroker#9]
It'd be awesome if you could add a judge for SMTP (supply a host as param).
You might be able to use aiosmtplib...
Tks!

**Comment by constverum** [comment]
Currently in development version 0.2 with several new features, including the check access to port 25. I think beta will be released one of these days.

**Comment by laruellef** [comment]
Any chance for christmas today? ;-)

**Comment by constverum** [comment]
And here is the first alpha version 0.2.0 branch (is unstable).

[Example of check proxies on work with SMTP protocol](https://github.com/constverum/ProxyBroker/blob/dev/examples/proxy_smtp_port.py).
Probably also need to add the check response code returned by the smtp server when connecting.

> pip install -U git+https://github.com/constverum/ProxyBroker.git@dev

**Comment by constverum** [comment]
Updated to 0.2.0b1, the documentation is also updated.

**Comment by laruellef** [comment]
Awesome job!!!
Question:
How do you consume these proxies found with type CONNECT:25?
These don't seem to be SOCKS proxies...
I'm unable to wrap smtplib with pysocks.

**Comment by constverum** [comment]
Thank you @laruellef =)

In version 0.2.0b2 verified only the response http status code from the proxy when connecting to the SMTP server (required 200). 

Above I wrote:
> Probably also need to add a verification response code returned by the SMTP server

In version 0.2.0b3 I added the check status code response of the SMTP server ([220](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#SMTP_transport_example)), not sure, but maybe I should also add the sending of EHLO/HELO command. Anyway, try to upgrade and check it.

> but it's not obvious how you are testing these buggers...
See [here](https://github.com/constverum/ProxyBroker/blob/master/proxybroker/negotiators.py#L109) and [test](https://github.com/constverum/ProxyBroker/blob/master/tests/test_negotiators.py#L169)
