### ISSUE TITLE
pip3 install proxybroker success, but command not found.

### ISSUE THREAD

**Issue by youshaoduo** [constverum/ProxyBroker#93]
System: MacOS Mojave

➜  Desktop proxybroker
zsh: command not found: proxybroker

**Comment by schobster** [comment]
Sounds like pip is installing proxybroker somewhere that is not on your PATH.

I recommend taking a look here to help track it down: https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

Once you find out where it's located, add the following to your `~/.zshrc`:
`export PATH=$PATH:<wherever it got installed>`

**Comment by constverum** [comment]
Sorry, I can't reproduce it =\ Tested on macos 10.14.3 (18D109).
Try to update to the latest version if the issue still exists.
